### your site title here

title: Dxartist | Disruptive Art
url: https://dxartist.com
enforce_ssl: dxartist.com
permalink: /:title
### exclude the instructions / write-up in the README.md

exclude:
- README.md

markdown: kramdown

sass: 
 style: compressed

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


gems: [jekyll-seo-tag, gemoji]