### your site title here

title: Dxartist | Disruptive Art
url: https://dxartist.com
enforce_ssl: dxartist.com
permalink: /:title
### exclude the instructions / write-up in the README.md

exclude:
- README.md


sass: 
 style: compressed
 
gems:
  - jekyll-seo-tag